version: '3.8'


services:
 

  nodeserver:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb

    ports:
      - 80:80

  mysqldb:
    image: mysql:9.0.1
    env_file:
      ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./src/mysql-init/:/docker-entrypoint-initdb.d/
volumes:
  db_data:
