openapi: 3.0.0
info:
  title: API de Mediciones
  description: API profesional para consultar y gestionar datos de mediciones, usuarios y nodos.
  version: 1.0.0
servers:
  - url: https://localhost
    description: Servidor local (HTTPS)
  - url: http://localhost
    description: Servidor local (HTTP)
tags:
  - name: Autenticación
    description: Rutas relacionadas con la autenticación de usuarios
  - name: Nodos
    description: Gestión de nodos en el sistema
  - name: Distancias diarias
    description: Operaciones con distancias diarias
  - name: Usuarios
    description: Gestión de usuarios
  - name: Mediciones
    description: Gestión de mediciones
security:
  - sessionCookieAuth: [] # Seguridad predeterminada para rutas protegidas
paths:
  # --- RUTAS DE AUTENTICACIÓN ---
  /auth/login:
    post:
      tags:
        - Autenticación
      summary: Inicia sesión
      operationId: login
      security: [ ] # Sin autenticación requerida
      requestBody:
        description: Datos de inicio de sesión
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_login'
      responses:
        "200":
          description: Sesión iniciada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  sessionId:
                    type: string
        "400":
          description: Datos de inicio de sesión inválidos
        "404":
          description: Usuario no encontrado
        "500":
          description: Error en el servidor
  /auth/register:
    post:
      tags:
        - Autenticación
      summary: Registra un nuevo usuario
      operationId: register
      security: [ ] # Sin autenticación requerida
      requestBody:
        description: Datos del nuevo usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users_post_put'
      responses:
        "201":
          description: Usuario registrado correctamente
        "400":
          description: Datos de usuario inválidos
        "409":
          description: Email ya registrado
        "500":
          description: Error en el servidor
  /auth/sendVerificationEmail:
    post:
      tags:
        - Autenticación
      summary: Envía un email de verificación
      operationId: sendVerificationEmail
      security: [ ] # Sin autenticación requerida
      parameters:
        - name: email
          in: query
          description: Email del usuario
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Email de verificación enviado correctamente
        "400":
          description: Email inválido
        "500":
          description: Error en el servidor
  /auth/resetPassword:
    post:
      tags:
        - Autenticación
      summary: Resetea la contraseña
      operationId: resetPassword
      security: [ ] # Sin autenticación requerida
      parameters:
        - name: email
          in: query
          description: Email del usuario
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Contraseña reseteada correctamente
        "400":
          description: Email inválido
        "404":
          description: Usuario no encontrado
        "500":
          description: Error en el servidor

  # --- RUTAS DE NODOS ---
  /nodes:
    get:
      tags:
        - Nodos
      summary: Obtiene un nodo por su UUID
      operationId: get_node
      parameters:
        - name: uuid
          in: query
          description: UUID del nodo a buscar
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Nodo obtenido correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nodes'
        "400":
          description: Parámetros de consulta inválidos
        "404":
          description: Nodo no encontrado
        "500":
          description: Error en el servidor
    post:
      tags:
        - Nodos
      summary: Crea un nuevo nodo
      operationId: create_node
      requestBody:
        description: Datos del nuevo nodo
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nodes'
      responses:
        "201":
          description: Nodo creado correctamente
        "400":
          description: Datos del nodo inválidos
        "500":
          description: Error en el servidor
    put:
      tags:
        - Nodos
      summary: Actualiza un nodo
      operationId: update_node
      requestBody:
        description: Datos del nodo a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nodes'
      responses:
        "202":
          description: Nodo actualizado correctamente
        "400":
          description: Datos del nodo inválidos
        "404":
          description: Nodo no encontrado
        "500":
          description: Error en el servidor
    delete:
      tags:
        - Nodos
      summary: Elimina un nodo
      operationId: delete_node
      parameters:
        - name: uuid
          in: query
          description: UUID del nodo a eliminar
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Nodo eliminado correctamente
        "400":
          description: Parámetros de consulta inválidos
        "404":
          description: Nodo no encontrado
        "500":
          description: Error en el servidor

  # --- RUTAS DE DISTANCIAS DIARIAS ---
  /daily_distance:
    get:
      tags:
        - Distancias diarias
      summary: Obtiene la distancia recorrida por un usuario en una fecha
      operationId: get_daily_distance
      parameters:
        - name: user_id
          in: query
          description: Identificador del usuario
          required: true
          schema:
            type: integer
        - name: date
          in: query
          description: Fecha de la distancia diaria
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Distancia diaria obtenida correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/daily_distance'
        "400":
          description: Parámetros de consulta inválidos
        "404":
          description: Distancia no encontrada
        "500":
          description: Error en el servidor
    post:
      tags:
        - Distancias diarias
      summary: Crea una nueva distancia diaria
      operationId: create_daily_distance
      requestBody:
        description: Datos de la nueva distancia diaria
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/daily_distance'
      responses:
        "201":
          description: Distancia diaria creada correctamente
        "400":
          description: Datos inválidos
        "500":
          description: Error en el servidor
  # --- RUTAS MEDICIONES ---
  /mediciones/diaria:
    get:
      tags:
        - Mediciones
      summary: Obtiene todas las medidas hechas en la fecha correspondiente
      operationId: get_mediciones_diarias
      parameters:
        - name: user_id
          in: cookie
          description: Identificador del usuario
          required: true
          schema:
            type: integer
        - name: date
          in: query
          description: Fecha de la distancia diaria
          required: true
          schema:
            type: string

      responses:
        200:
          description: OK
        400:
          description: La fecha no esta bien escrita
        401:
          description: Sin autorización





components:
  schemas:
    user_login:
      type: object
      properties:
        email:
          type: string
          description: Email del usuario
        password:
          type: string
          description: Contraseña del usuario
      example:
        email: "juan@email.com"
        password: "123456"
    users_post_put:
      type: object
      properties:
        name:
          type: string
          description: Nombre del usuario
        email:
          type: string
          description: Email del usuario
        password:
          type: string
          description: Contraseña del usuario
        surname_1:
          type: string
          description: Apellido del usuario
        surname_2:
          type: string
          description: Segundo apellido del usuario
        telephone:
          type: string
          description: Teléfono del usuario  
      required:
        - email
        - name
        - password
        - surname_1
        - telephone
      example:
        name: "Juan"
        email: "juan@email.com"
        password: "Juan 2024"
        surname_1: "Pérez"
        surname_2: "García"
        telephone: "622334455"
    nodes:
      type: object
      properties:
        id:
          type: integer
          description: Identificador del nodo
        uuid:
          type: string
          description: UUID del nodo
      example:
        id: 1
        uuid: "123456789"
    daily_distance:
      type: object
      properties:
        id:
          type: integer
          description: Identificador de la distancia diaria
        date:
          type: string
          description: Fecha de la distancia diaria
        distance:
          type: number
          description: Distancia recorrida en kilómetros
      example:
        id: 1
        date: "2024-11-18"
        distance: 12.5
  securitySchemes:
    sessionCookieAuth:
      type: apiKey
      in: cookie
      name: connect.sid
