/*
 * @Author: Alex Escrivà Caravaca 
 * @Date: 2024-10-06 16:57:44 
 * @Last Modified by: Alex Escrivà Caravaca
 * @Last Modified time: 2024-10-06 16:58:07
 */
 
-- MySQL Script generated by MySQL Workbench
-- Sun Oct  6 11:47:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MeidcionesGas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MeidcionesGas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MedicionesGas` DEFAULT CHARACTER SET utf8 ;
USE `MedicionesGas` ;

-- -----------------------------------------------------
-- Table `MedicionesGas`.`Mediciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MedicionesGas`.`Mediciones` (
  `idMediciones` INT NOT NULL AUTO_INCREMENT,
  `medida` DOUBLE ZEROFILL NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `tipo_gas` VARCHAR(45) NOT NULL,
  `hora` DATETIME NOT NULL,
  PRIMARY KEY (`idMediciones`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
